### ISSUE TITLE
Incorporate AR Aging to the PB Universe Prototype

### ISSUE THREAD

**Issue by Domokin** [Domokin/Benchmark#21]
- [x] Import AR Transactions Data Mart

**Comment by MHildebrand1** [comment]
In progress

**Comment by MHildebrand1** [comment]
Universe model updated based on recent change of ARTransactions table name to ARAgingHistory and built dimensions around newly added keys in the fact table.

**Comment by MHildebrand1** [comment]
Full AR Aging model pulled into the UMG PB Benchmarks universe and modeled accordingly. Summary fact tables for Department and Division have also been integrated with aggregate awareness.
