### ISSUE TITLE
Design PB Universe Prototype Benchmark Summary Business Layer

### ISSUE THREAD

**Issue by Domokin** [Domokin/Benchmark#24]
Benchmark Summary
- [x] Element Definitions
- [x] Element Names
- [x] Element Structure

**Comment by MHildebrand1** [comment]
Summary tables completely integrated into AR subject area with aggregate awareness along Department, Division and Provider grains.

**Comment by MHildebrand1** [comment]
Summary tables completely integrated into AR subject area with aggregate awareness along Department, Division and Provider grains. Business Layer definitions not entirely appropriate task for this as summary tables will be abstracted from the user. Meaning, they will not be accessing Summary specific objects from the business layer.
