### ISSUE TITLE
Address how to deal with new Departments in Benchmark Report

### ISSUE THREAD

**Issue by Domokin** [Domokin/Benchmark#39]

**Comment by Johnsay1** [comment]
Tammy only wants to see departments that have benchmarks set.

**Comment by Johnsay1** [comment]
Pending confirmation about the group total. Should it include new departments?

**Comment by Johnsay1** [comment]
Met and discussed with Tammy. Confirmed, the actual totals for the group should include new departments, but departments with no benchmarks should not appear on the report. We discussed "new" departments that might have originally been included in another department's benchmarks, but it was still decided they should not appear on the report.
