### ISSUE TITLE
Revisions to AR universe

### ISSUE THREAD

**Issue by Johnsay1** [Domokin/Benchmark#48]
- [x] Add metrics for % AR > 90/120/180 (in addition to the existing totals). I'm guessing there will need to be some extensive testing re: aggregate awareness to ensure that if attributes are added together, the percentages calculate correctly?

- [ ] Currently only AR folders are exposed, but some of the folders/attributes will be shared between AR and Billing Transaction Fact (BTF) and some will not. We should restructure the folders/attributes to group Shared vs AR vs BTF. Let's discuss in our next sprint and come up with the proper naming conventions and structure. 

- [x] The AR Greater Than 90/120/180 Totals are not working at the detail level. Mary and I discussed this and it appears to be a result of the conversion of the flag from Yes/No to 0/1. They are set properly in the summary table, but not the detail.

**Comment by Johnsay1** [comment]
![detailbinary error](https://cloud.githubusercontent.com/assets/26314196/25865516/fa8eb592-34a7-11e7-87cb-eb46784c1086.JPG)

This is the error that I am received when I try to pull from the detail table.

**Comment by MHildebrand1** [comment]
Corrected the Yes/No flag issue on the AR detail fact. Also included the additional totals for 30, 60, 90, 150, etc breakouts as well as the corresponding percentages
